// This file is auto-generated by @hey-api/openapi-ts

export type User = {
  id: string;
  name: string;
  email: string;
};

export type CreateUser = {
  name: string;
  email: string;
};

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type GetApiUsersByIdResponses = {
  /**
   * User found
   */
  200: User;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PostApiUsersData = {
  body?: CreateUser;
  path?: never;
  query?: never;
  url: '/api/users';
};

export type PostApiUsersResponses = {
  /**
   * User created
   */
  201: User;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type ClientOptions = {
  baseUrl: 'https://localhost:3001' | (string & {});
};
