-- Extend scheduler season config to persist scheduler UI settings

ALTER TABLE schedulerseasonconfig
  ADD COLUMN umpirespergame SMALLINT NOT NULL DEFAULT 2,
  ADD COLUMN maxgamesperumpireperday SMALLINT;

CREATE TABLE schedulerseasonleagueselections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accountid BIGINT NOT NULL,
  seasonid BIGINT NOT NULL,
  leagueseasonid BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  createdat TIMESTAMPTZ NOT NULL DEFAULT now(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_schedulerseasonleagueselections_accounts
    FOREIGN KEY (accountid) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedulerseasonleagueselections_season
    FOREIGN KEY (seasonid) REFERENCES season(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedulerseasonleagueselections_leagueseason
    FOREIGN KEY (leagueseasonid) REFERENCES leagueseason(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_schedulerseasonleagueselections_season_leagueseason
  ON schedulerseasonleagueselections(seasonid, leagueseasonid);

CREATE INDEX idx_schedulerseasonleagueselections_accountid
  ON schedulerseasonleagueselections(accountid);

CREATE INDEX idx_schedulerseasonleagueselections_seasonid
  ON schedulerseasonleagueselections(seasonid);

CREATE INDEX idx_schedulerseasonleagueselections_leagueseasonid
  ON schedulerseasonleagueselections(leagueseasonid);

