name: Auto-merge PRs

on:
  workflow_run:
    workflows: ["PR Validation"]
    types:
      - completed

jobs:
  auto-merge:
    name: Auto-merge approved PRs
    runs-on: ubuntu-latest
    
    # Only run if the PR validation workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get PR information
        id: pr-info
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Checking for auto-merge eligible PRs...');
            console.log(`Branch: ${context.payload.workflow_run.head_branch}`);
            console.log(`Head reference: ${context.repo.owner}:${context.payload.workflow_run.head_branch}`);
            
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`,
              state: 'open'
            });
            
            if (prs.length === 0) {
              console.log('❌ No open PR found for this branch');
              return null;
            }
            
            const pr = prs[0];
            console.log(`✅ Found PR #${pr.number}: ${pr.title}`);
            console.log(`PR labels: ${pr.labels.map(l => l.name).join(', ') || 'none'}`);
            
            // Check if PR has auto-merge label
            const hasAutoMergeLabel = pr.labels.some(label => 
              label.name === 'auto-merge' || label.name === 'automerge'
            );
            
            if (!hasAutoMergeLabel) {
              console.log('❌ PR does not have required auto-merge label ("auto-merge" or "automerge")');
              console.log('Available labels:', pr.labels.map(l => l.name).join(', ') || 'none');
              return null;
            }
            
            console.log('✅ PR has auto-merge label');
            console.log(`Initial PR mergeable: ${pr.mergeable}`);
            console.log(`Initial PR mergeable_state: ${pr.mergeable_state}`);
            
            // Get detailed PR information with retry logic for mergeable state
            // GitHub computes mergeable state asynchronously, so we may need to wait
            let detailedPR;
            let retries = 0;
            const maxRetries = 5;
            
            while (retries < maxRetries) {
              console.log(`🔄 Fetching detailed PR info (attempt ${retries + 1}/${maxRetries})...`);
              
              const { data } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });
              
              detailedPR = data;
              console.log(`Detailed PR mergeable: ${detailedPR.mergeable}`);
              console.log(`Detailed PR mergeable_state: ${detailedPR.mergeable_state}`);
              
              // If mergeable state is available and not null, we're good
              if (detailedPR.mergeable !== null && detailedPR.mergeable_state !== null) {
                console.log('✅ Got complete mergeable state information');
                break;
              }
              
              retries++;
              
              // Wait before retrying (GitHub needs time to compute mergeable state)
              if (retries < maxRetries) {
                console.log('⏳ Mergeable state not ready, waiting 10 seconds before retry...');
                await new Promise(resolve => setTimeout(resolve, 10000));
              }
            }
            
            if (retries >= maxRetries) {
              console.log('⚠️ Max retries reached, proceeding with available data');
            }
            
            const finalMergeable = detailedPR.mergeable;
            const finalMergeableState = detailedPR.mergeable_state;
            
            console.log(`📊 Final PR state: mergeable=${finalMergeable}, mergeable_state=${finalMergeableState}`);
            
            return {
              number: detailedPR.number,
              mergeable: finalMergeable,
              mergeable_state: finalMergeableState,
              retries_used: retries
            };
            
      - name: Auto-merge PR
        if: steps.pr-info.outputs.result != 'undefined' && steps.pr-info.outputs.result != '' && steps.pr-info.outputs.result != 'null'
        uses: actions/github-script@v7
        with:
          script: |
            let prInfo;
            try {
              const result = '${{ steps.pr-info.outputs.result }}';
              if (!result || result === 'undefined' || result === 'null' || result === '') {
                console.log('No valid PR information available, skipping');
                return;
              }
              prInfo = JSON.parse(result);
            } catch (error) {
              console.log('Failed to parse PR information:', error.message);
              return;
            }
            
            if (!prInfo) {
              console.log('No PR information available, skipping');
              return;
            }
            
            const { number, mergeable, mergeable_state, retries_used } = prInfo;
            
            console.log(`🔍 Processing PR #${number}`);
            console.log(`📊 Mergeable: ${mergeable}`);
            console.log(`📊 Mergeable state: ${mergeable_state}`);
            console.log(`🔄 Retries used: ${retries_used || 0}`);
            
            // Check if mergeable state is still unknown
            if (mergeable === null || mergeable_state === null) {
              console.log(`⚠️ PR #${number} mergeable state is still unknown after retries`);
              console.log(`  - mergeable: ${mergeable}`);
              console.log(`  - mergeable_state: ${mergeable_state}`);
              console.log('❌ Cannot proceed with auto-merge due to unknown state');
              return;
            }
            
            // Check if PR is not mergeable
            if (!mergeable) {
              console.log(`❌ PR #${number} is not mergeable (mergeable: ${mergeable})`);
              return;
            }
            
            // Check if mergeable state is not clean
            if (mergeable_state !== 'clean') {
              console.log(`❌ PR #${number} mergeable state is not clean (state: ${mergeable_state})`);
              console.log('   Expected: "clean", but got:', mergeable_state);
              
              // Log common mergeable states for debugging
              const commonStates = {
                'dirty': 'PR has conflicts that need to be resolved',
                'unknown': 'GitHub is still computing the mergeable state',
                'blocked': 'PR is blocked by required status checks',
                'behind': 'PR branch is behind the base branch',
                'unstable': 'Required status checks are failing'
              };
              
              if (commonStates[mergeable_state]) {
                console.log(`   Reason: ${commonStates[mergeable_state]}`);
              }
              
              return;
            }
            
            console.log(`✅ PR #${number} is ready for auto-merge!`);
            
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: number,
                merge_method: 'squash',
                commit_title: `Auto-merge PR #${number}`,
                commit_message: `🤖 Auto-merged after successful validation\n\nGenerated with [Claude Code](https://claude.ai/code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>`
              });
              
              console.log(`Successfully auto-merged PR #${number}`);
              
            } catch (error) {
              console.log(`Failed to auto-merge PR #${number}: ${error.message}`);
              
              // Comment on the PR about the failure
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                body: `⚠️ Auto-merge failed: ${error.message}\n\nPlease merge manually or check the requirements.`
              });
            }